// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SaveRecipeController from "./controllers/save_recipe_controller"

const application = Application.start()
application.register("save-recipe", SaveRecipeController)

ApplicationController.register('MealPlanRecipesController', MealPlanRecipesController)
